- hosts: db-01.local
  become: true
  become_method: sudo
  tasks:
    - name: "Update packages and upgrade"
      apt:
        update_cache: true
        upgrade: dist
        force_apt_get: true
    - name: "Set a hostname"
      ansible.builtin.hostname:
        name: db-01
        use: systemd
    - name: "Install a list of packages"
      ansible.builtin.apt:
        pkg:
        - avahi
        - postgresql
        - git
    - name: "Clone repo"
      ansible.builtin.git:
        repo: https://github.com/ZfauX/bingo.git
        dest: /home/ubuntu
    - name: "Copy Cert File If Different"
      copy:
        src: /home/ubuntu/bingo/ssl/server_db1/server1.crt
        dest: /etc/ssl/certs/server.crt
        mode: 0644
        owner: postgres
        group: postgres
    - name: "Copy Key File If Different"
      copy:
        src: /home/ubuntu/bingo/ssl/server_db1/server1.key
        dest: /etc/ssl/private/server.key
        mode: 0600
        owner: postgres
        group: postgres  
    - name: "Copy Cert File If Different"
      copy:
        src: /home/ubuntu/bingo/ssl/root/root.crt
        dest: /etc/ssl/private/root.crt
        mode: 0644
        owner: ubuntu
        group: ubuntu
    - name: "Copy config File If Different"
      copy:
        src: /home/ubuntu/bingo/postgresql/master/pg_hba.conf
        dest: /etc/postgresql/14/main/pg_hba.conf
        mode: 0644
        owner: postgres
        group: postgres
    - name: "Copy config File If Different"
      copy:
        src: /home/ubuntu/bingo/postgresql/master/postgresql.conf
        dest: /etc/postgresql/14/main/postgresql.conf
        mode: 0644
        owner: postgres
        group: postgres   
    - name: "Copy script File If Different"
      copy:
        src: /home/ubuntu/bingo/postgresql/script.sql
        dest: /var/lib/postgresql/14/main/script.sql
        mode: 0644
        owner: postgres
        group: postgres       
    - name: "Create Directories"
      file:
        path: "{{ item }}"
        state: directory
        owner: postgres
        group: postgres
        mode: 0755
      loop:
        - '/opt/pg_archives/'
    - name: "Restart service postgresql on ubuntu, in all cases, also issue daemon-reload to pick up config changes"
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: postgresql
    - name: "Execute the command in remote shell; stdout goes to the specified file on the remote"
      ansible.builtin.shell: sudo -u postgres psql -f /var/lib/postgresql/14/main/script.sql